mongo:
  uri:
  database:

discord:
  token:
  serverid:
  verificationChannel:
  trustedStaffId:
  staffId:
  adminChannel:
  chatbotChannel:
  openaiToken:
  shiftChannel:
  awaitingVerificationRole:
  verifiedRole:
